apiVersion: v1
entries:
  prometheus:
  - apiVersion: v1
    appVersion: 2.21.0
    created: "2020-10-06T15:19:14.2772414+09:00"
    dependencies:
    - condition: kubeStateMetrics.enabled
      name: kube-state-metrics
      repository: https://dragoneena12.github.io/helm-repo/
      version: 3.0.0
    description: Prometheus is a monitoring system and time series database.
    digest: 0a659dbff7b9115011e496051de1165ac86e66add312b3fcfe6f57d41215504f
    home: https://prometheus.io/
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    maintainers:
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    - email: monotek23@gmail.com
      name: monotek
    - email: naseem@transit.app
      name: naseemkullah
    name: prometheus
    sources:
    - https://github.com/prometheus/alertmanager
    - https://github.com/prometheus/prometheus
    - https://github.com/prometheus/pushgateway
    - https://github.com/prometheus/node_exporter
    - https://github.com/kubernetes/kube-state-metrics
    urls:
    - prometheus-11.16.2.tgz
    version: 11.16.2
generated: "2020-10-06T15:19:14.2704863+09:00"
